In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr2 = np.array([[34,52,68,55],[77,66,12,39]])

print(arr[4])

print(arr[2:])

print(arr[:2])

print(arr2[:1])

5
[3 4 5 6 7]
[1 2]
[[34 52 68 55]]


In [4]:
print(arr2[:,:-1])

[[34 52 68]
 [77 66 12]]
